#If debug mode should be activated (just for testing and troubleshooting)
Debug_Mode = false

["Self-Revive Settings"]

	["Self-Revive Settings"."General Settings"]
		#List of all your self-revive options (Duplicate options are allowed). Self-revive options refresh from this list when the revive penalty ends.
		# OPTIONS: CHANCE, RANDOM_ITEMS, SPECIFIC_ITEM, KILL, STATUS_EFFECTS, EXPERIENCE
		SELF_REVIVE_OPTIONS = ["SPECIFIC_ITEM", "RANDOM_ITEMS", "CHANCE", "KILL", "STATUS_EFFECTS", "EXPERIENCE"]
		#Max self revives (setting to 0 will disable self-revive) (setting to -1 will disable the self-revive max) (In multiplayer self-revive will only be disabled when you reach the max) Refreshes when penalty timer ends.
		#Range: > -1
		Max_Self_revives = 3
		#If self-revive should be disabled if a player places you in the fallen state
		Disable_Self_Revive_On_PVP = false
		#If the chosen self-revive options are picked randomly.
		Randomize_Self_Revive_Options = true
		#If the mod should only pick self-revive options that you would meet the requirements for (when possible)
		Only_Use_Available_Options = false
		#Increases the cost of self-revival options each time you self-revive. Stacks additively. Resets to 0 on fallen penalty timer expiration.
		#Range: 0.0 ~ 1.0
		Self_Penalty_Percentage = 0.25

	["Self-Revive Settings"."Revive Type Settings"]

		["Self-Revive Settings"."Revive Type Settings".Chance]
			#How high your chance is to revive. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			Revive_Chance = 0.75

		["Self-Revive Settings"."Revive Type Settings"."Random Items"]
			#Percentage to lose for sacrificial items. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			Item_Loss_Percentage = 0.25

		["Self-Revive Settings"."Revive Type Settings"."Specific Item"]
			#Item that you wish to sacrifice. Usage: MODID:ITEM
			Item_ID = "minecraft:golden_apple"
			#How much of the specific item is needed.
			#Range: > 0
			Item_Count = 3
			#NBT Data for the specific item
			Item_Data = "{}"

		["Self-Revive Settings"."Revive Type Settings".Kill]
			#Amount of Living Entities you must kill before the death timer runs out.
			#Range: > 0
			Kill_Count = 2
			#Time in SECONDS you have to kill the needed amount of Living Entities. (Affected by penalty)
			#Range: > 0
			Kill_Time = 20

		["Self-Revive Settings"."Revive Type Settings"."Status Effects"]
			#List of harmful effects that shouldn't be chosen. Usage: (ModId:PotionEffect)(minecraft:slowness)
			Harmful_Effects_Blacklist = ["minecraft:unluck", "minecraft:instant_damage"]
			#How long the harmful effects will last for. (Affected by penalty)
			#Range: > 0
			Effect_Duration = 12
			#If Revive effects should be disabled when reviving with this self-revive type.
			Disable_Revive_Effects = true

		["Self-Revive Settings"."Revive Type Settings".XP]
			#Percentage of XP you should lose to revive. (Affected by penalty)
			#Range: 0.0 ~ 1.0
			XP_Loss_Percentage = 0.4000000059604645
			#The minimum amount of XP levels needed.
			#Range: > 0
			Minimum_XP_Level = 15

["Fallen State Settings"]

	["Fallen State Settings"."General Settings"]
		#If the Living Death Event should run first before this mod does (if Death event runs first and player death is cancelled, Revive-Me code will not execute. Same thing vice-versa.)
		Run_Death_Event_First = true
		#If you can give up and die
		Can_Give_Up = true
		#If you should instantly die if you disconnect while in the fallen state
		Die_On_Disconnect = false
		#If the player can use their inventory while fallen
		#Allowed Values: NO, LOOK_ONLY, YES
		Interact_With_Inventory = "LOOK_ONLY"
		#Potion effects the player has while fallen (ModId:PotionEffect:Amplification)(minecraft:slowness:0)
		Downed_Effects = ["minecraft:slowness:3"]
		#Commands the player isn't allowed to use while fallen. Type "/" to block all commands.
		Blocked_Commands = []
		#Keybinds that you can use while in the fallen state. (You can put a piece or the full name of a keybind. (Check the translation json for keybinding names (en_us.json for example))
		#Example of binding: 'key.fullscreen' or 'fullscreen' will let you use the 'Toggle Fullscreen' keybinding while in the fallen state)
		Allowed_Keybinds = []
		#How long before you can call for help again in SECONDS
		#Range: 0.0 ~ 1.7976931348623157E308
		Revive_Help_Call_Cooldown = 0.75
		#How long the Help call effects will last in SECONDS
		#Range: 0.0 ~ 1.7976931348623157E308
		Revive_Help_Duration = 8.0

	["Fallen State Settings"."Timer Settings"]
		#How long you have before death. Default is 30 seconds. Setting to 0 will disable the timer
		#Range: > 0
		Time_Left = 60
		#How much time (in seconds) your death timer loses each time you fall. (Less than 1 is a percentage of max death time, -1 will take away the max)
		#Range: -1.0 ~ 1.7976931348623157E308
		Time_Reduction_Penalty = 5.0
		#how long the revive penalty effects will last in SECONDS
		#Range: 0.0 ~ 1.7976931348623157E308
		Revive_Penalty_Timer = 45.0
		#How much time (in seconds) must pass before you may be killed by other players. Affected by time reduction penalty. Setting to -1 will disable this
		#Range: > -1
		PVP_Timer = 10

	["Fallen State Settings"."Movement Settings"]
		#What pose you have whilst fallen
		#Allowed Values: CROUCH, PRONE, SLEEP
		Fallen_Pose = "CROUCH"
		#If the player may jump while fallen
		#Allowed Values: YES, LIQUID_ONLY, NO
		Can_Jump = "YES"
		#If the player may move while fallen
		Can_Move = true

["Revive Settings"]

	["Revive Settings"."Revivee Settings"]
		#How much health you will be revived with, -1 is max health, Less than 1 is percentage
		#Range: -1.0 ~ 2.147483647E9
		Revive_Health = 10.0
		#How much food you will be revived with, -1 is max food, Less than 1 is percentage
		#Range: -1.0 ~ 2.147483647E9
		Revive_Food = 6.0
		#How many seconds of invulnerability you have on revive
		#Range: 0.0 ~ 3.4028234663852886E38
		Revive_Invuln_Time = 5.0
		#Give back all of the potion effects the player had before entering the fallen state
		Revert_Effects_On_Revive = false

	["Revive Settings"."Reviver Settings"]
		#How long to revive someone
		#Range: > 0
		Revive_Time = 3
		#What the reviver will lose
		#Allowed Values: NONE, HEALTH, EXPERIENCE, FOOD, ITEM
		Penalty_Type = "ITEM"
		#Amount that will be taken from reviver, Numbers below 1 and greater than 0 will turn it into a percentage
		Penalty_Amount = 10.0
		#Item used to revive fallen players (Only if you selected ITEM as penalty type). Usage: MODID:ITEM
		Revive_Item = "ambulance:first_aid_kit"
		#Item data used to revive fallen players (Only if you selected ITEM as penalty type).
		Revive_Item_Data = "{}"
		#If revive should be cancelled when taking damage
		Cancel_Revive_On_Damage = false

["Chat Settings"]
	#Silence the revive and fallen chat messages
	Silence_Regular_Messages = false
	#Silence command chat messages
	Silence_Command_Messages = false
	#If chat messages from this mod should be sent to everyone. If false, will only send to those nearby
	Universal_Chat_Messages = false

["Client Settings"]
	#Makes self-revive UI smaller, more compact
	Compact_UI = false
	#Controls how loud Revive Me! sounds are
	#Range: 0.0 ~ 1.0
	Sound_Level = 0.699999988079071

